create table if not exists payments (
  id bigint generated by default as identity primary key,
  month text not null,
  lakber numeric not null,
  kk numeric not null,
  gaz numeric not null,
  villany numeric not null,
  viz numeric not null,
  notes text,
  reference_number text,
  created_at timestamp with time zone default timezone('utc'::text, now())
); 