-- Reset everything
drop policy if exists "Enable read access for all users" on payments;
drop policy if exists "Enable insert access for all users" on payments;
drop table if exists payments;

-- Create table
create table payments (
    id bigint generated by default as identity primary key,
    month text not null,
    lakber numeric not null,
    kk numeric not null,
    gaz numeric not null,
    villany numeric not null,
    viz numeric not null,
    notes text,
    reference_number text,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Enable RLS
alter table payments enable row level security;

-- Create policies
create policy "Enable read access for all users"
on payments for select
to anon
using (true);

create policy "Enable insert access for all users"
on payments for insert
to anon
with check (true); 